import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { Tinos, Homemade_Apple, Kalam } from "next/font/google"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const tinos = Tinos({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-tinos", // Define the CSS variable name
})

const kalam = Kalam({
  weight: ["300", "400", "700"], // Multiple weights are good for handwriting
  subsets: ["latin"],
  variable: "--font-kalam",
})

// 3. Configure Homemade Apple (Handwriting)
const homemadeApple = Homemade_Apple({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-homemade", // Define the CSS variable name
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tinos.variable} ${homemadeApple.variable} ${kalam.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}
